name: DVAE11
dependencies:
  - python=3.9  # Specify the Python version you're using
  - pip  # Ensures pip is available for installing packages
  - pip:
      - pandas>=1.3.0
      - numpy>=1.21.0
      - scikit-learn>=0.24.0
      - sdv>=1.2.0
      - PyYAML>=6.0
      - matplotlib>=3.4.0
      - seaborn>=0.11.0
      - jupyter
