folders:
  source_file: "./data/Nifty.csv"

dataset:
  date_col: "Date"
  date_format: "%d-%m-%Y"
  normalize_columns: ['Open', 'High', 'Low', 'Close']
  SID: "SID"
  
  
preprocessing:
  unwanted_columns: [] 
  normalization_method: "minmax"
  categorical_columns: []
  window_size: 50
  step_size: 1
  
metadata:
  seq_key: "SID"
  seq_index: "Date"

synthesizer:
  context_columns: []
  epochs: [1]
  verbose: True
  cuda: True

evaluation:
  exclude_cols: ['Date','Next_Day', 'SID']
  top_peaks: 5

classification:
    param_grid:
          n_neighbors:
            - 1
            - 3
            - 5
            - 7
            - 9
          weights:
            - uniform
            - distance
          distance:
            - dtw 
            - shape_dtw  
            - ddtw 
            - wdtw 
            - wddtw
            - adtw
            - erp
            - edr
            - msm
            - twe
            - lcss
            - euclidean 
            - squared
            - manhattan
            - minkowski
            - sbd
            - shift_scale
            - soft_dtw
            
    test_size: 0.2
    random_state: 0
    target_col:  'Next_Day'


correlation_analysis:
    metric_columns: ["MSAS", "AWD", "TC"]


logging:
  log_file: "logs/pipeline.log"
  level: "INFO"
