data:
  input_path: "data/real_data.csv"
  output_path: "data/synthetic_data.csv"
  metadata_path: "data/metadata.json"
  preprocessing:
    remove_columns: ["NSM", "Day_of_Week"]
    normalization: "minmax"  # Options: minmax, standard

synthesizer:
  context_columns: ["Load_Type", "WeekStatus"]
  epochs: 60
  cuda: true

generation:
  num_sequences: 1457
  sequence_length: 96

evaluation:
  metrics: ["population_fidelity", "classification_utility"]

logging:
  log_file: "logs/pipeline.log"
  level: "INFO"
