data:
  input_path: "./data/real_data.csv"
  output_path: "./data/synthetic_data.csv"
  
preprocessing:
  input_file: "./data/source.csv"  # Path to the input file
  output_file: "./data/real_data.csv"  # Path to the output file
  unwanted_columns:  # List of columns to drop
    - "NSM"
    - "WeekStatus"
    - "Day_of_week"
  date_column: "date"  # The name of the date column
  categorical_columns:  # List of categorical columns
    - "Load_Type"
  window_size: 96  # Size of the sliding window
  step_size: 24    # Step size for the sliding window
  normalization_method: "minmax"  # Normalization method (e.g., minmax or z-score)

metadata:
  seq_key: "SID"
  seq_index: "date"
  date_format: "%d/%m/%Y %H:%M"
  metadata_path: "./data/metadata.json"

synthesizer:
  context_columns: []
  epochs: [ 1 ]
  verbose: true
  cuda: true
  model_output: './outputs/Models/synthesizer.pkl'

generation:
  num_sequences: 1457
  sequence_length: 96

evaluation:
  PF_results: './outputs/Evaluation/MSAS.csv'
  synth_folder: './outputs/Synth_Data/'
  awd_output: './outputs/Evaluation/AWD.csv'
  msas_output: './outputs/Evaluation/MSAS.csv'

  
  sid_col: 'SID'
  f1_ratios_path: './outputs/Evaluation/f1_ratios.csv'
  metric_file_path: './outputs/Evaluation/AWD.csv'
  metric_column: 'AWD'
  plot_output_path: './outputs/Plots/'
  exclude_cols: 
      - 'date'
      - 'Load_Type'
      - 'SID'

classification:
    param_grid:
          n_neighbors:
            - 1
            - 3
            - 5
            - 7
          weights:
            - uniform
            - distance
          distance:
            - euclidean
            - squared
            - manhattan
    test_size: 0.25
    random_state: 0
    seq_index_col: 'SID' 
    target_col:  'Load_Type'
    metric: 'f1'



correlation_analysis:


logging:
  log_file: "logs/pipeline.log"
  level: "INFO"
