folders:
  source_file: "./data/Steal.csv"

dataset:
  date_col: "date"
  date_format: "%d/%m/%Y %H:%M"
  normalize_columns: ['Usage_kWh', 'Lagging_Current_Reactive.Power_kVarh', 'Leading_Current_Reactive_Power_kVarh', 
                    'CO2(tCO2)', 'Lagging_Current_Power_Factor', 'Leading_Current_Power_Factor']
  
preprocessing:
  unwanted_columns: ["NSM", "WeekStatus", "Day_of_week"]
  normalization_method: "minmax" 
  categorical_columns: 
    - 'Load_Type'
  window_size: 48
  step_size: 12

metadata:
  seq_key: "SID"
  seq_index: "date"

synthesizer:
  context_columns: []
  epochs: [100, 500, 1000, 1500, 2000, 2500, 5000, 10000]
  verbose: True
  cuda: True

evaluation:
  exclude_cols: ['date','Load_Type', 'SID']

classification:
    param_grid:
      n_neighbors:
        - 3
        - 7
        - 11
      weights:
        - uniform
        - distance
      distance:
        - euclidean
        - squared
        - dtw
    test_size: 0.25
    random_state: 0
    target_col:  'Load_Type'

logging:
  log_file: "logs/pipeline.log"
  level: "INFO"