folders:
  source_file: "./data/Nifty.csv"

dataset:
  date_col: "Date"
  date_format: "%d-%m-%Y"
  normalize_columns: ['Open', 'High', 'Low', 'Close']
  
preprocessing:
  unwanted_columns: [] 
  normalization_method: "minmax"
  categorical_columns: []
  window_size: 50
  step_size: 1
  
metadata:
  seq_key: "SID"
  seq_index: "Date"

synthesizer:
  context_columns: []
  # 16 Epochs [1, 2, 4, 8, 16, 32, 64, 100, 250, 500, 1000, 1500, 2000, 2500, 5000, 10000]
  epochs: [1, 2, 4, 8, 16, 32, 64, 100, 250, 500, 1000, 1500, 2000, 2500, 5000, 10000]
  verbose: True
  cuda: True

evaluation:
  exclude_cols: ['Date','Next_Day', 'SID']

classification:
    param_grid:
      n_neighbors:
        - 3
        - 7
        - 11
      weights:
        - uniform
        - distance
      distance:
        - euclidean
        - squared
        - dtw
    test_size: 0.2
    random_state: 0
    target_col:  'Next_Day'

logging:
  log_file: "logs/pipeline.log"
  level: "INFO"
