folders:
  source_file: "./data/Nifty.csv"

dataset:
  date_col: "Date"
  date_format: "%d-%m-%Y"
  numerical_col: ['Open', 'High', 'Low', 'Close']
  SID: "SID"
  
  
preprocessing:
  unwanted_columns: [] 
  normalization_method: "minmax"  # Normalization method (e.g., minmax or z-score)
  categorical_columns: []
  window_size: 50
  step_size: 1
  
metadata:
  seq_key: "SID"
  seq_index: "Date"

synthesizer:
  context_columns: []
  epochs: [1]
  verbose: True
  cuda: True

evaluation:
  exclude_cols: ['Date','Next_Day', 'SID']
  top_peaks: 5

classification:
    param_grid:
          n_neighbors:
            - 1
            - 3
            - 5
            #- 7
          weights:
            - uniform
            - distance
          distance:
            #- dtw # fast
            #- shape_dtw # Takes too much time 
            #- ddtw # fast & great result
            #- wdtw # fast & good result 
            #- wddtw
            #- adtw
            #- erp
            #- edr
            #- msm
            #- twe
            #- lcss
            - euclidean 
            #- squared
            #- manhattan
            #- minkowski
            #- sbd
            #- shift_scale
            #- soft_dtw
            
    test_size: 0.25
    random_state: 0
    target_col:  'Next_Day'
    metric: 'f1'


correlation_analysis:
    metric_columns: ["MSAS", "AWD", "TC"]


logging:
  log_file: "logs/pipeline.log"
  level: "INFO"
